### ISSUE TITLE
support GHC version 8.10 & 8.8

### ISSUE THREAD

**Issue by ghorn** [tweag/rules_haskell#1327]
GHC 8.10.1 was released in March. This feature request is to add support to that compiler version.
Relevant issues are:
https://github.com/tweag/rules_haskell/issues/1290
https://github.com/tweag/rules_haskell/issues/1324
https://github.com/tweag/rules_haskell/issues/1323

**Comment by guibou** [comment]
Note that GHC 8.10 is unofficially working for normal build, but indeed, there is some issue with profiling build.

**Comment by aherrmann** [comment]
It's worth pointing out that there is no [Stackage snapshot](https://www.stackage.org/) (nightly or LTS) available for GHC 8.10, yet. Meaning that an upgrade at this point is more likely to cause issues with Hackage dependencies due to version bounds or package incompatibilities. It would also require for users to define a custom snapshot for the `stack_snapshot` rule. If possible, It's usually preferable to wait with the upgrade until a Stackage snapshot is available.

**Comment by guibou** [comment]
@aherrmann the problem listed here are also existing with ghc 8.8 unfortunately, for which there is a stackage snapshot.

**Comment by guibou** [comment]
Note:

- 4c997fae9d1fc9dfc66b2cc9214f96199907399c, from junary, was working fine with GHC 8.8 and 8.10 (with custom patchs for our codebase, such as https://github.com/tweag/rules_haskell/pull/1169
- current master (a5a550874d5be8852755bd9bfe3f6d9a8d3ba793) does not work anymore with GHC 8.10 (with or without the custom patchs) with the following linking errors:

```
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_decodeDoublezu2Intzh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_casArrayzh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_casSmallArrayzh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_newArrayArrayzh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_copyArrayArrayzh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_copyMutableArrayArrayzh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_casMutVarzh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_compactNewzh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_compactResizzezh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_compactContainszh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_compactContainsAnyzh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_compactGetFirstBlockzh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_compactGetNextBlockzh'
/nix/store/mc2ymhld0nrssch577i8d5bk5m5k2r7b-ghc-8.10.1/lib/ghc-8.10.1/ghc-prim-0.6.1/libHSghc-prim-0.6.1-ghc8.10.1.so: error: undefined reference to 'stg_compactAllocateBlockzh'
```

**Comment by aherrmann** [comment]
@guibou This looks like an instance of https://github.com/tweag/rules_haskell/issues/1401. Can you confirm whether it works with https://github.com/tweag/rules_haskell/pull/1388 patched out, or a rules_haskell revision just before #1401 was merged?

**Comment by guibou** [comment]
@aherrmann indeed, using the commit just before #1401 solved the problem. 5073048c9e307295ea1102459e214750d6a118ad Thank you.

**Comment by mboes** [comment]
> current master (a5a5508) does not work anymore with GHC 8.10

@guibou can you confirm that since #1424, this is no longer an issue? If so, I'd suggest closing this ticket and opening new ones with more focused issue descriptions if there are problems with GHC 8.8 still. The title of this issue mentions 8.8 but not the description.

**Comment by Xophmeister** [comment]
GHC 8.8 support added in v0.12; 8.10 support added in v0.13.

I will close this issue unless @guibou asserts otherwise.
