### ISSUE TITLE
Breakage with Bazel@HEAD

### ISSUE THREAD

**Issue by lberki** [tweag/rules_haskell#1495]
`rules_haskell` is broken on the continuous integration tests of Bazel @ HEAD:

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1903#81e5c204-6ddf-4452-85a5-65b950176c5a

This breakage is probably caused by https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1903#81e5c204-6ddf-4452-85a5-65b950176c5a that calls test binaries in external repositories not using their legacy `external/$REPO/$REPO_RELATIVE_PATH` path but the canonical `../$REPO/$REPO_RELATIVE_PATH` one.

I haven't looked into what the mechanism of the breakage is; my guess is that test binaries try to find data files relative to $0 and that logic needs to be updated

This issue is also available in our continuous-integration repository as bazelbuild/continuous-integration#1090 .

**Comment by gyias** [comment]
FYI, I ran a downstream CI with https://github.com/bazelbuild/bazel/commit/00805727b867d33fd922e63ca82b0d9825ad79fe reverted, but they're still broken.

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1919#6740cd90-e323-4070-889d-7f9924c04f8b

**Comment by aherrmann** [comment]
Thanks for reporting!

I'm afraid I don't understand some of the linked CI logs:
- https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1903#81e5c204-6ddf-4452-85a5-65b950176c5a
  Shows failures in a project called Tulsi. I'm not sure how that relates to rules_haskell.

Looking at the [Bazel CI status on master](https://buildkite.com/bazel/rules-haskell-haskell/builds/650#609603b8-9e20-498c-85d4-aaf75ff89100) I noticed failures that may be due to our [recent work](https://github.com/tweag/rules_haskell/pull/1484) on expanding the number of tests we run in non-Nix mode. I forgot to update the Bazel CI tag filters accordingly. I [started a pipeline](https://buildkite.com/bazel/rules-haskell-haskell/builds/652#fead514e-defc-463a-ae6d-6544d94ce1c2) to see if that fixes the issue.

**Comment by comius** [comment]
The proper link is https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1921#bc106604-da66-465b-8e9b-173766815ae5

**Comment by comius** [comment]
Breakage is caused by https://github.com/bazelbuild/bazel/commit/7149f578006a4ad0d51df69830a6986749b34df5

**Comment by aherrmann** [comment]
I see, thanks for clarifying. In that case the issue solved by #1496 seems unrelated.

Are there instructions somewhere on how to reproduce these test runs locally for debugging purposes?

**Comment by comius** [comment]
Following was used for rules_gwt, I haven't tried it, but might work for haskell as well.

```
USE_BAZEL_VERSION=7149f578006a4ad0d51df69830a6986749b34df5 
bazel clean && bazel build --disk_cache=/tmp/bazel_disk_cache //tests/...
```

**Comment by comius** [comment]
After https://github.com/bazelbuild/bazel/commit/7149f578006a4ad0d51df69830a6986749b34df5 the error is different, see below.

Full log at https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1924#8f955628-60b7-4249-8925-a7daabe7efd1

```
exe/Main.hs:671:24: error:
--
  | • Exception when trying to run compile-time code:
  | /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/18c25b4026b5f422e1efd6536818b1cd/execroot/rules_haskell/external/rules_haskell_ghc_linux_amd64/bin/../lib/settings: openFile: does not exist (No such file or directory)
  | Code: makeGhcVersionChecker (pure <$> getLibdir)
  | • In the Template Haskell splice
  | $$(makeGhcVersionChecker (pure <$> getLibdir))
  | In the expression: $$(makeGhcVersionChecker (pure <$> getLibdir))
  | In an equation for ‘ghcVersionChecker’:
  | ghcVersionChecker = $$(makeGhcVersionChecker (pure <$> getLibdir))
  | \|
  | 671 \| ghcVersionChecker = $$(makeGhcVersionChecker (pure <$> getLibdir))
  | \|                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/6d66f770f087e3aa3ec33d66ffb996f0/sandbox/linux-sandbox/1895/execroot/rules_haskell/bazel-out/host/bin/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 194, in <module>
  | run([runghc] + runghc_args + [setup, "build", "--verbose=0", "--builddir=" + distdir])
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/6d66f770f087e3aa3ec33d66ffb996f0/sandbox/linux-sandbox/1895/execroot/rules_haskell/bazel-out/host/bin/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 42, in run
  | subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, *args, **kwargs)
  | File "/usr/lib/python3.6/subprocess.py", line 438, in run
  | output=stdout, stderr=stderr)



```
exe/Main.hs:671:24: error:
--
  | • Exception when trying to run compile-time code:
  | /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/18c25b4026b5f422e1efd6536818b1cd/execroot/rules_haskell/external/rules_haskell_ghc_linux_amd64/bin/../lib/settings: openFile: does not exist (No such file or directory)
  | Code: makeGhcVersionChecker (pure <$> getLibdir)
  | • In the Template Haskell splice
  | $$(makeGhcVersionChecker (pure <$> getLibdir))
  | In the expression: $$(makeGhcVersionChecker (pure <$> getLibdir))
  | In an equation for ‘ghcVersionChecker’:
  | ghcVersionChecker = $$(makeGhcVersionChecker (pure <$> getLibdir))
  | \|
  | 671 \| ghcVersionChecker = $$(makeGhcVersionChecker (pure <$> getLibdir))
  | \|                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/6d66f770f087e3aa3ec33d66ffb996f0/sandbox/linux-sandbox/1895/execroot/rules_haskell/bazel-out/host/bin/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 194, in <module>
  | run([runghc] + runghc_args + [setup, "build", "--verbose=0", "--builddir=" + distdir])
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/6d66f770f087e3aa3ec33d66ffb996f0/sandbox/linux-sandbox/1895/execroot/rules_haskell/bazel-out/host/bin/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 42, in run
  | subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, *args, **kwargs)
  | File "/usr/lib/python3.6/subprocess.py", line 438, in run
  | output=stdout, stderr=stderr)
```

**Comment by aherrmann** [comment]
@comius Thanks for the update. We've had issues like this one on BazelCI before, see https://github.com/tweag/rules_haskell/issues/1470, and had fixed it in https://github.com/tweag/rules_haskell/pull/1478. AFAIK, the issue has not reappeared on BazelCI since. What are the differences between BazelCI and Bazel@HEAD?

I've tried to reproduce the issue locally with 
```
$ export USE_BAZEL_VERSION=7149f578006a4ad0d51df69830a6986749b34df5
$ bazel version
2021/02/24 12:02:08 Using unreleased version at commit 7149f578006a4ad0d51df69830a6986749b34df5
$ bazel build @ghcide-exe//ghcide
$ bazel build //tests/ghc-check/...
```
(The latter is a regression test we introduced for this issue in https://github.com/tweag/rules_haskell/pull/1478)
But, these builds all pass just fine locally.

Looking at the sandbox working directories with the flags `--sandbox_debug -s`, I see that the file `.../sandbox/linux-sandbox/128/execroot/rules_haskell/external/rules_haskell_ghc_linux_amd64/bin/../lib/settings` is present. Using `bazel aquery @ghcide//:_ghcide_exe_ghcide` I can see that `external/rules_haskell_ghc_linux_amd64/lib/settings` is an input to the action.

**Comment by Wyverald** [comment]
The latest failures have yet another different set of error messages -- and what's more, the failures seem a bit flaky.

* 2021-02-24 (Wed): [Failed](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1930#15c60b96-d5a1-4c09-9df1-e7a060330ee5) at //tests/ghc-check:ghc-check (error log follows)
  ```
  exec ${PAGER:-/usr/bin/less} "$0" || exit 1
  Executing tests from //tests/ghc-check:ghc-check
  -----------------------------------------------------------------------------
  ghc-check: user error (GHC installation not found in libdir: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite- agent/60bb93ce05fa74e94efdf5bd06a733ff/execroot/rules_haskell/external/rules_haskell_ghc_linux_amd64/bin/../lib)
  ```
* 2021-02-23 (Tue): [Passed](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1928#f3a45ba6-1256-45d8-9ad4-f11cb2058ba1) somehow
* 2021-02-22 (Mon): [Failed](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1927#5a08ab3e-c964-4093-8bf9-e92a20d58c8a) at //tests/ghc-check:ghc-check (same error as above)
* Same failure (ghc-check) on Sat & Sun
* Before that, the failure was different (see Ivo's comment https://github.com/tweag/rules_haskell/issues/1495#issuecomment-782042203)

**Comment by aherrmann** [comment]
Thanks for collecting more data on this. The flakiness is consistent with what we saw in https://github.com/tweag/rules_haskell/issues/1470, as mentioned in https://github.com/tweag/rules_haskell/issues/1470#issuecomment-756663131. The different errors are, I think, different symptoms of the same issue. We introduced the `ghc-check` test in https://github.com/tweag/rules_haskell/pull/1478, it runs the same code that triggers the `ghcide` issue shown in https://github.com/tweag/rules_haskell/issues/1495#issuecomment-782042203. `ghc-check` is easier to iterate on as it has far fewer dependencies than `ghcide`, which is pretty huge. `bazel aquery` confirms that `external/rules_haskell_ghc_linux_amd64/lib/settings` is also a declared input to the compile and link actions for the `ghc-check` test.

**Comment by meteorcloudy** [comment]
I did a bit debugging on this. I think the problem is that the linking action somehow leaked an absolute path into the cached artifacts.

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1936#aa5dc341-4051-46f0-9260-3285c50b34cb

If you look carefully at the error message:
```
(cd /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/de1ad6465cc0956998cd702123d7aa2b/sandbox/linux-sandbox/1154/execroot/rules_haskell && ...
```
The real execroot for this action is under /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/**de1ad6465cc0956998cd702123d7aa2b**.

But in the error message, it complains:
```
proto-lens-protoc: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/802d931a6749cc0eb9d3ff1d4dd67a37/execroot/rules_haskell/external/rules_haskell_ghc_linux_amd64/bin/../lib/settings: openFile: does not exist (No such file or directory)
```
Which is under /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/**802d931a6749cc0eb9d3ff1d4dd67a37**. This path is likely from a previous builds with a different Bazel binary. Although the Bazel binary is different, there still could be a cache hit. However, the cached binary (proto-lens-protoc) expects to find the `settings` file under the non-exist absolute path.

Any idea how this could happen in the build?

**Comment by meteorcloudy** [comment]
Possibly the following?
https://github.com/tweag/rules_haskell/blob/c075f915deb67f94b95fc3e9334baa3809133a64/haskell/cabal.bzl#L392-L395

**Comment by aherrmann** [comment]
> I think the problem is that some action somehow leaked an absolute path into the cached artifacts.

@meteorcloudy Thank you for digging further into this! Yes, this makes sense. Sorry, I should have noticed this before, but didn't see it. The `ghc-check` package uses the `ghc-paths` package which hard codes the path to the GHC installation at build time. The use-case is for tooling like IDE integration which needs to know the path to the compiler installation. This works fine for global GHC installations in `/usr` or in the Nix store, but this does not work for GHC installations in the execroot, as is the case with the bindist toolchain used here.

We'll need to think a bit about how to fix this issue. One potential idea would be to replace `ghc-paths` by a version that is patched to work with Bazel. It would probably need to declare a runtime dependency on the GHC installation and it's version of `GHC.Paths.libdir` and so on could use `rlocation` to find the GHC installation. However, I'm wary of tracking the GHC distribution in runfiles. Bazel creates deep symlink trees for runfiles dependencies which can take up a lot of space and time if they are big, see e.g. https://github.com/tweag/rules_nixpkgs/pull/103 where this caused out-of-disk-space errors on CI with the Python toolchain.

**Comment by aherrmann** [comment]
@meteorcloudy I've implemented the workaround described above in https://github.com/tweag/rules_haskell/pull/1508. The PR passes on our CI and on [Bazel CI](https://buildkite.com/bazel/rules-haskell-haskell/builds/679). Could I ask you to run Bazel@HEAD against this PR to see if it resolves the issue on Bazel@HEAD?

**Comment by meteorcloudy** [comment]
@aherrmann Thanks, Andreas! I'm available (forgot to clear my github status). 

I've launched two tests with Bazel@HEAD in the rules_haskell pipelines (by setting USE_BAZEL_VERSION=last_green).
master branch: https://buildkite.com/bazel/rules-haskell-haskell/builds/680
bazel-head branch: https://buildkite.com/bazel/rules-haskell-haskell/builds/681

The master branch failed as expected while the bazel-head branch passed. So looks like your fix works! ;)

**Comment by aherrmann** [comment]
:tada: Awesome, thank you @meteorcloudy for testing it so quickly!

> I've launched two tests with Bazel@HEAD in the rules_haskell pipelines (by setting USE_BAZEL_VERSION=last_green).

That's good to know, thanks for pointing this out.

**Comment by vladmos** [comment]
A friendly reminder that rules_haskell is still red at the Bazel CI, keeping it red for a long time makes it harder to detect new regressions if there are any.

**Comment by aherrmann** [comment]
@vladmos Thank you for the reminder. #1508 is now merged. Hopefully that resolves the issue.

**Comment by vladmos** [comment]
@aherrmann Unfortunately it's still broken, even after a manual remote cache invalidation: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1965#fcd9ab2a-b5a8-4711-bcb6-308b364e0285 . Could you please take a look at the issue again?

**Comment by aherrmann** [comment]
@vladmos Is this testing rules_haskell on latest master (183f7f3e9889f2108984ad27efea1cbd51657d42), i.e. including #1508? I'm asking because #1508 adds the test-case [`//tests/ghc-check:ghc-check-cabal-test`](https://github.com/tweag/rules_haskell/pull/1508/files#diff-fe166c00474b1fbbf178a14554002a8aac95f9db44559ba243d7b3103ded6e95R40) and I don't see it listed [in the log](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1965#fcd9ab2a-b5a8-4711-bcb6-308b364e0285/343-480). To be sure I reran BazelCI on rules_haskell master with `USE_BAZEL_VERSION=last_green`. In that case the test-case [is listed in the log](https://buildkite.com/bazel/rules-haskell-haskell/builds/695#7495943e-1cb8-4f70-8933-1febce32a69f/313-386) and CI passes.

**Comment by vladmos** [comment]
For some reason it still fetches and old commit for testing (https://github.com/tweag/rules_haskell/commit/43d0af16fed9eb8e470a9dd599c403df7096e248), not sure why.

**Comment by vladmos** [comment]
Perhaps the reason was that I launched the tests after the pull request had been merged, but before it was tested separately, your commit hadn't been yet marked as green.

Launched the tests again, hopefully they'll pass: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1966

P.S. it looks that the test failure is flaky, the previous run is also green now after a couple retries: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1965

**Comment by vladmos** [comment]
The tests pass now. Because of the previous problem was flaky it's worth keeping an eye on it for a few days but for now you can assume the issue is fixed.
