### PR TITLE
Runtime behavior of tests are checked

### PR DESCRIPTION
**Pull request by guibou**
Previously, only build of `haskell_binary` / `haskell_library` was
tested. Hence runtime link issues (or others issues) were ignored, see
for example bug #537.

This commit changes, when possible, `haskell_binary` to `haskell_test`
which means that binaries are also executed during the test process to
ensure their correct runtime behavior.

--

Current status of this PR: Cannot be merged

The following tests are failing due to the runtime tests, a checked box means that it was corrected

- [X] This PR will fail 5 tests until #537 is fixed. #550 can be a good temporary solution. #550 is now merged.
- [X] There is also another failing test due to runtime detection of character encoding. Fixed in this PR
- [x] runtime failure on darwin only of `//tests/indirect-link:indirect-link`

### CODE REVIEW

**Comment by guibou** [comment]
```
Executing tests from //tests/indirect-link:indirect-link
-----------------------------------------------------------------------------
dyld: lazy symbol binding failed: Symbol not found: _real_get_thing
  Referenced from: /private/var/tmp/_bazel_distiller/bedaa68a8664d1b29e96b826d058247f/execroot/io_tweag_rules_haskell/bazel-out/darwin-fastbuild/bin/tests/indirect-link/../../../../../bazel-out/darwin-fastbuild/bin/tests/indirect-link/libcbits.so
  Expected in: flat namespace

dyld: Symbol not found: _real_get_thing
  Referenced from: /private/var/tmp/_bazel_distiller/bedaa68a8664d1b29e96b826d058247f/execroot/io_tweag_rules_haskell/bazel-out/darwin-fastbuild/bin/tests/indirect-link/../../../../../bazel-out/darwin-fastbuild/bin/tests/indirect-link/libcbits.so
  Expected in: flat namespace
```

Still failing on darwin.

**Comment by guibou** [comment]
Darwin failure bisected to:

```
50160fc1bf5423f08e4fa84750d31bd668fcc6db is the first bad commit
commit 50160fc1bf5423f08e4fa84750d31bd668fcc6db
Author: Joe Kachmar <joseph.kachmar@gmail.com>
Date:   Tue Dec 11 16:32:51 2018 -0500

    Adds new GHC bindists

:040000 040000 7bb3eea1e8f257062ca4e35f0b676fe220e7d9e1 3384aa6ad26265951ca6c7c32bf8ab664399166f M	haskell
```

**Comment by guibou** [comment]
The test `//tests/indirect-link:indirect-link` was introduced by:

```
commit 336d5f348afad74d3c01d8c166517ffe002ed973
Author: Guillaume Bouchard <guillaume.bouchard@tweag.io>
Date:   Thu Aug 9 17:21:15 2018 +0200

    Add test provided by #170
```

and had never fully worked on darwin. Meaning that #170 is not closed yet.

**Comment by Profpatsch** [comment]
I commented out the `indirect-link` test, it should be fixed in a separate PR.
