### PR TITLE
Only pass -no-pie for binary targets

### LINKED ISSUE #1418: haskell_cabal_library linker errors when using GHC 8.10
**Describe the bug**
Building even a simple `haskell_cabal_library` fails with linker errors when using GHC 8.10. The same code built without Cabal does not lead to linker errors.

**To Reproduce**
Switch `rules_haskell` to GHC 8.10.1 or 8.10.2. Then,

```
$ bazel build @stackage//:void
[undefined reference to various RTS symbols errors]
```

**Expected behavior**
I expect the build to succeed with no linker errors.

**Environment**
 - OS name + version: NixOS 20.03 (using a Nixpkgs toolchain) or Debian buster (using GHC bindists).

**Additional context**
This bug has already been reported multiple times: see #1401 #1413 #1327. I'm creating a new issue to gather what we know in a single place, with a more focused issue description.

According to https://github.com/tweag/rules_haskell/issues/1327#issuecomment-664378765, this is a regression introduced by #1388, which is itself necessary on some systems when using GHC 8.8. Since we don't use GHC 8.10 during CI testing, we didn't catch this.

On a PIE-by-default systems like Debian Buster,
* building a `haskell_library` using GHC 8.8 works fine, with or without #1388,
* building a `haskell_cabal_library` using GHC 8.8 works fine, with or without #1388,
* building a `haskell_library` using GHC 8.10 works fine, with or without #1388,
* building a `haskell_cabal_library` using GHC 8.10 works but only without #1388.

The latter case also fails on NixOS with a Nixpkgs toolchain.

So what's still unclear is why the result matrix for `haskell_cabal_library` is different on GHC 8.8 and on GHC 8.10. It's likely that https://gitlab.haskell.org/ghc/ghc/-/issues/15319 has something to do with it.

What's also unclear is why for GHC 8.10, the result matrix is different for `haskell_library` and `haskell_cabal_library`. The former works after #1388 while the latter does not.

cc @patrickt @robinbb

### PR DESCRIPTION
**Pull request by mboes**
When using GHC 8.10, passing `-no-pie` to the linker when building
libraries leads to obscure linker errors. Since PIE pertains to
executables, it doesn't make much sense passing that flag when
building libraries anyways. Removing it, both for `haskell_library`
and `haskell_cabal_library` fixes GHC 8.10 support. We make sure to
keep the flag for executables. This would otherwise negate the effect
of #1388.

Fixes #1418

### CODE REVIEW

**Comment by mboes** [comment]
This PR does not change the compiler version used during testing. We still test with GHC 8.8.3 only, whereas the bug the PR is fixing only appears on GHC 8.10.*. @patrickt you may also want to confirm that this fixes the linker errors you saw when then moving Semantic to GHC 8.10.

**Review by guibou — APPROVED** [review]
LGTM for the change. I'm surprised because I'm using GHC 8.10 with rules_haskell since it was released and I never had this issue on Linux.

So there may be an additional requirement (not just GHC 8.10) which triggers this issue.

**Comment by patrickt** [comment]
Doesn’t seem to work on our end just yet: `ld` is dying with 
```
/usr/bin/ld: -r and -pie may not be used together
```

Full backscroll here: https://github.com/github/semantic/pull/627/checks?check_run_id=1123152233

**Comment by mboes** [comment]
@patrickt I see that error with GHC 8.8 but not 8.10. Are you sure you are using 8.10? For 8.8, I'll push a workaround to the workaround. The logic is getting really complex, all to paper over a lack of proper solution to https://gitlab.haskell.org/ghc/ghc/-/issues/15319. I think we should tackle that next.

**Comment by patrickt** [comment]
It seems to be working now!! You’re the best, @mboes! And indeed, linker errors are my least favorite part of programming.
